spring:
  application:
    name: fintech

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      show-sql: false

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migrations
